name: Terraform

on:
  push:
    branches: [main]
    paths:
      - "infrastructure/terraform/**"
      - ".github/workflows/terraform.yml"
  pull_request:
    branches: [main]
    paths:
      - "infrastructure/terraform/**"
      - ".github/workflows/terraform.yml"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform:
    uses: Xomware/github-actions/.github/workflows/terraform.yml@v1
    with:
      app: smirnoff
      working-directory: infrastructure/terraform
